version: "3.8"

networks:
  docker-network:

volumes:
  database-data:

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webserver
    command: gunicorn -b :8000 -w 1 --timeout 200 weather.wsgi:application
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - docker-network
  database:
    image: postgres:16-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test"]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - docker-network